{
    'name': 'History Of patients',
    'version': '1.0.1',
    'author': 'Hammal Solutions',
    'summary': 'Gestión de pacientes y sincronización Jira',
    'depends': ['base', 'web', 'iap', 'mail', 'project','hr_timesheet'], 
    'data': [
        'security/ir.model.access.csv',
        'views/odontograma_view.xml',
        'views/pacientesView.xml',
        'views/views.xml',
        'views/jira_project_view.xml',
        'data/data.xml',
        'data/estadosVenezuela.xml',
        'views/principalMenuView.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mi_modulo_prueba/static/src/css/odontograma.css',
            'mi_modulo_prueba/static/src/js/odontograma_widget.js',
            'mi_modulo_prueba/static/src/xml/odontograma_template.xml',
            'mi_modulo_prueba/static/src/css/audio_recorder.css',
            'mi_modulo_prueba/static/src/js/audio_recorder.js',
            'mi_modulo_prueba/static/src/xml/audio_recorder.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}